version: '3.9'

services:
  busy:
    container_name: busy
    image: davidreinberger/plex-tdarr-busy
    restart: always
    environment:
      - "CRON=*/5 * * * * *"
      - TDARR_URL=192.168.0.131:8265
      - TDARR_NODE=MainNode
      - PLEX_URL=192.168.0.131:32400
      - PLEX_TOKEN=rndpsiJztQsyxxszVXd7
      - BUSY_VIDEO_URL=/library/other/busy.mp4
