name: Build & Deplo

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build And Deploy Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: davidreinberger/plex-tdarr-busy

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: davidreinberger/plex-tdarr-busy:latest
          labels: ${{ steps.meta.outputs.labels }}
